services:    
  vuejs_lms:
    build: .
    container_name: vuejs_lms
    image: vuejs_lms:01
    volumes:
      - .:/var/www/html/vuejs_lms
    command: php artisan serve --host 0.0.0.0 --port=5003 & npm run dev --host 0.0.0.0 --port=8080
    network_mode: host
