services:    
  vuejs_lms:
    build: .
    container_name: vuejs_lms
    image: vuejs_lms
    restart: always
    volumes:
      - .:/var/www/html/vuejs_lms
    ports:
      - 3005:80
      - 5173:5173
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - mysql_database

networks:
  mysql_database:
    external: true